### ISSUE TITLE
Undefined method "utc" with "from" parameter

### ISSUE THREAD

**Issue by bbpennel** [projectblacklight/blacklight_oai_provider#47]
In our hyrax 4 application, which is using blacklight-oai-provider 7.0.2, we are getting periodic errors like the following:
```
NoMethodError (undefined method `utc' for Sat, 04 Nov 2023:Date):
  
blacklight_oai_provider (7.0.2) lib/blacklight_oai_provider/resumption_token.rb:38:in `encode_conditions'
blacklight_oai_provider (7.0.2) lib/blacklight_oai_provider/resumption_token.rb:46:in `to_xml'
oai (1.2.1) lib/oai/provider/response/list_records.rb:37:in `block (2 levels) in to_xml'
builder (3.2.4) lib/builder/xmlbase.rb:176:in `_nested_structures'
builder (3.2.4) lib/builder/xmlbase.rb:69:in `tag!'
builder (3.2.4) lib/builder/xmlbase.rb:94:in `method_missing'
oai (1.2.1) lib/oai/provider/response/list_records.rb:26:in `block in to_xml'
oai (1.2.1) lib/oai/provider/response.rb:40:in `block in response'
builder (3.2.4) lib/builder/xmlbase.rb:176:in `_nested_structures'
builder (3.2.4) lib/builder/xmlbase.rb:69:in `tag!'
oai (1.2.1) lib/oai/provider/response.rb:37:in `response'
oai (1.2.1) lib/oai/provider/response/list_records.rb:25:in `to_xml'
oai (1.2.1) lib/oai/provider.rb:443:in `list_records'
oai (1.2.1) lib/oai/provider.rb:469:in `process_request'
blacklight_oai_provider (7.0.2) app/controllers/concerns/blacklight_oai_provider/controller.rb:18:in `oai'
```
which appear to occur when clients provide a `from` parameter specified as a date rather than a date+time, like the following:
`/catalog/oai?verb=ListRecords&metadataPrefix=oai_dc&from=2023-11-04`

The error only seems to occur if the result would return enough results to trigger resumption token behaviors. I'm not sure where it's happening in the stack, but it would seem that when the `from` (or `until`) field doesn't specify time of day, it gets deserialized as a Date, while when it is specified as a full UTC timestamp (with Z as the timezone) it gets deserialized as a DateTime. Only the latter has a `utc` method.

**Comment by laritakr** [comment]
### UTC encode bug
The bug above is that encode_conditions calls `from.utc` and `self.until.utc`. 

On the first request, from/until are Date objects (set by the parent OAI::Provider::ResumptionToken from the OAI gem's parameter parsing). Date has no .utc method → crash.

On resumed requests, parse_date converts them to Time via ActiveSupport::TimeZone.new('UTC').parse(str), so they'd be fine. But it never gets that far because the first token creation fails.

Date#to_time returns a Time at midnight, which has .utc. Works for both Date and Time inputs (.to_time on a Time is a no-op).

### Date selection bug
Additionally, the resumption token doesn't process dates the same as the initial search does. The full search includes the full day on the from value, but the resumption token uses it as the beginning of the day. 

### Fix for both of above

```
    def encode_conditions
      encoded_token = @prefix.to_s.dup
      encoded_token << ".s(#{set})" if set
      encoded_token << ".f(#{date_to_time(from).utc.xmlschema})" if from
      encoded_token << ".u(#{date_to_time(self.until, end_of_day: true).utc.xmlschema})" if self.until
      encoded_token << ".t(#{total})" if total
      encoded_token << ":#{last}"
    end

    private

    def date_to_time(value, end_of_day: false)
      return value unless value.is_a?(Date) && !value.is_a?(Time)

      if end_of_day
        value.to_time(:utc).end_of_day
      else
        value.to_time(:utc)
      end
    end
```
